# Generated by Django 5.2.4 on 2025-07-16 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='watchagain',
            new_name='watchAgain',
        ),
    ]
